const elements = [
    { symbol: "H", name: "Hydrogen", atomicNumber: 1, atomicMass: "1.008", groupBlock: "Nonmetal", electronConfiguration: "1s1", uses: "Rocket fuel, welding", facts: "Lightest and most abundant element in the universe." },
    { symbol: "He", name: "Helium", atomicNumber: 2, atomicMass: "4.0026", groupBlock: "Noble Gas", electronConfiguration: "1s2", uses: "Balloons, deep-sea diving tanks", facts: "Second most abundant element in the universe." },
    { symbol: "Li", name: "Lithium", atomicNumber: 3, atomicMass: "6.94", groupBlock: "Alkali Metal", electronConfiguration: "1s2 2s1", uses: "Batteries, mood stabilizers", facts: "Lightest metal, highly reactive." },
    { symbol: "Be", name: "Beryllium", atomicNumber: 4, atomicMass: "9.0122", groupBlock: "Alkaline Earth Metal", electronConfiguration: "1s2 2s2", uses: "Aerospace materials, X-ray windows", facts: "Toxic in high concentrations." },
    { symbol: "B", name: "Boron", atomicNumber: 5, atomicMass: "10.81", groupBlock: "Metalloid", electronConfiguration: "1s2 2s2 2p1", uses: "Glass, detergents, fertilizers", facts: "Used in neutron capture therapy for cancer." },
    { symbol: "C", name: "Carbon", atomicNumber: 6, atomicMass: "12.011", groupBlock: "Nonmetal", electronConfiguration: "1s2 2s2 2p2", uses: "Organic compounds, steel manufacturing", facts: "Life's fundamental building block." },
    { symbol: "N", name: "Nitrogen", atomicNumber: 7, atomicMass: "14.007", groupBlock: "Nonmetal", electronConfiguration: "1s2 2s2 2p3", uses: "Fertilizers, explosives, cryogenics", facts: "Makes up 78% of Earth's atmosphere." },
    { symbol: "O", name: "Oxygen", atomicNumber: 8, atomicMass: "15.999", groupBlock: "Nonmetal", electronConfiguration: "1s2 2s2 2p4", uses: "Respiration, water, combustion", facts: "Essential for life on Earth." },
    { symbol: "F", name: "Fluorine", atomicNumber: 9, atomicMass: "18.998", groupBlock: "Halogen", electronConfiguration: "1s2 2s2 2p5", uses: "Toothpaste, refrigerants, Teflon", facts: "Most reactive element." },
    { symbol: "Ne", name: "Neon", atomicNumber: 10, atomicMass: "20.180", groupBlock: "Noble Gas", electronConfiguration: "1s2 2s2 2p6", uses: "Signs, lights", facts: "Glows red-orange when electrified." },
    { symbol: "Na", name: "Sodium", atomicNumber: 11, atomicMass: "22.990", groupBlock: "Alkali Metal", electronConfiguration: "1s2 2s2 2p6 3s1", uses: "Salt, soap, glass", facts: "Highly reactive with water." },
    { symbol: "Mg", name: "Magnesium", atomicNumber: 12, atomicMass: "24.305", groupBlock: "Alkaline Earth Metal", electronConfiguration: "1s2 2s2 2p6 3s2", uses: "Alloys, fireworks, photosynthesis", facts: "Burns with a bright white flame." },
    { symbol: "Al", name: "Aluminum", atomicNumber: 13, atomicMass: "26.982", groupBlock: "Post-Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p1", uses: "Packaging, transport, aerospace", facts: "Most abundant metal in the Earth's crust." },
    { symbol: "Si", name: "Silicon", atomicNumber: 14, atomicMass: "28.085", groupBlock: "Metalloid", electronConfiguration: "1s2 2s2 2p6 3s2 3p2", uses: "Semiconductors, solar cells", facts: "Second most abundant element in the Earth's crust." },
    { symbol: "P", name: "Phosphorus", atomicNumber: 15, atomicMass: "30.974", groupBlock: "Nonmetal", electronConfiguration: "1s2 2s2 2p6 3s2 3p3", uses: "Fertilizers, detergents", facts: "Comes in white, red, and black forms." },
    { symbol: "S", name: "Sulfur", atomicNumber: 16, atomicMass: "32.06", groupBlock: "Nonmetal", electronConfiguration: "1s2 2s2 2p6 3s2 3p4", uses: "Sulfuric acid, vulcanization of rubber", facts: "Found in nature as a yellow mineral." },
    { symbol: "Cl", name: "Chlorine", atomicNumber: 17, atomicMass: "35.45", groupBlock: "Halogen", electronConfiguration: "1s2 2s2 2p6 3s2 3p5", uses: "Water purification, bleach", facts: "Used as a chemical warfare agent in WWI." },
    { symbol: "Ar", name: "Argon", atomicNumber: 18, atomicMass: "39.948", groupBlock: "Noble Gas", electronConfiguration: "1s2 2s2 2p6 3s2 3p6", uses: "Inert gas for welding, light bulbs", facts: "Third most abundant gas in Earth's atmosphere." },
    { symbol: "K", name: "Potassium", atomicNumber: 19, atomicMass: "39.098", groupBlock: "Alkali Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s1", uses: "Fertilizers, salt substitutes", facts: "Highly reactive with water." },
    { symbol: "Ca", name: "Calcium", atomicNumber: 20, atomicMass: "40.078", groupBlock: "Alkaline Earth Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2", uses: "Bones, cement, lime", facts: "Found in limestone and marble." },
    { symbol: "Sc", name: "Scandium", atomicNumber: 21, atomicMass: "44.956", groupBlock: "Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d1", uses: "Aerospace, sports equipment", facts: "Rare and expensive." },
    { symbol: "Ti", name: "Titanium", atomicNumber: 22, atomicMass: "47.867", groupBlock: "Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d2", uses: "Aircraft, medical implants", facts: "Highly corrosion-resistant." },
    { symbol: "V", name: "Vanadium", atomicNumber: 23, atomicMass: "50.9415", groupBlock: "Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d3", uses: "Steel, titanium alloys", facts: "Used in superconductors." },
    { symbol: "Cr", name: "Chromium", atomicNumber: 24, atomicMass: "52.0", groupBlock: "Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d5", uses: "Plating, stainless steel", facts: "Highly resistant to corrosion." },
    { symbol: "Mn", name: "Manganese", atomicNumber: 25, atomicMass: "54.938044", groupBlock: "Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d5", uses: "Steel production, batteries", facts: "Important for bone health." },
    { symbol: "Fe", name: "Iron", atomicNumber: 26, atomicMass: "55.845", groupBlock: "Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d6", uses: "Steel, hemoglobin", facts: "Most used metal in the world." },
    { symbol: "Co", name: "Cobalt", atomicNumber: 27, atomicMass: "58.933", groupBlock: "Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d7", uses: "Batteries, magnets", facts: "Toxic if inhaled." },
    { symbol: "Ni", name: "Nickel", atomicNumber: 28, atomicMass: "58.693", groupBlock: "Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d8", uses: "Coins, alloys", facts: "Commonly used in stainless steel." },
    { symbol: "Cu", name: "Copper", atomicNumber: 29, atomicMass: "63.546", groupBlock: "Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10", uses: "Wires, coins", facts: "Best conductor of electricity." },
    { symbol: "Zn", name: "Zinc", atomicNumber: 30, atomicMass: "65.38", groupBlock: "Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10", uses: "Galvanization, alloys", facts: "Essential nutrient for humans." },
    { symbol: "Ga", name: "Gallium", atomicNumber: 31, atomicMass: "69.723", groupBlock: "Post-Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p1", uses: "Electronics, LED lights", facts: "Melts just above room temperature." },
  { symbol: "Ge", name: "Germanium", atomicNumber: 32, atomicMass: "72.63", groupBlock: "Metalloid", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p2", uses: "Semiconductors, infrared optics", facts: "Used in transistors and diodes." },
  { symbol: "As", name: "Arsenic", atomicNumber: 33, atomicMass: "74.922", groupBlock: "Metalloid", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3p3", uses: "Pesticides, wood preservatives", facts: "Highly toxic element." },
  { symbol: "Se", name: "Selenium", atomicNumber: 34, atomicMass: "78.971", groupBlock: "Nonmetal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3p4", uses: "Solar cells, photocopiers", facts: "Essential nutrient in trace amounts." },
  { symbol: "Br", name: "Bromine", atomicNumber: 35, atomicMass: "79.904", groupBlock: "Halogen", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3p5", uses: "Flame retardants, water purification", facts: "Only nonmetal that is a liquid at room temperature." },
  { symbol: "Kr", name: "Krypton", atomicNumber: 36, atomicMass: "83.798", groupBlock: "Noble Gas", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3p6", uses: "Fluorescent lamps, high-performance light bulbs", facts: "Rare in Earth's atmosphere." },
  { symbol: "Rb", name: "Rubidium", atomicNumber: 37, atomicMass: "85.468", groupBlock: "Alkali Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s1", uses: "Research, special glasses", facts: "Highly reactive and rare." },
  { symbol: "Sr", name: "Strontium", atomicNumber: 38, atomicMass: "87.62", groupBlock: "Alkaline Earth Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2", uses: "Fireworks, magnets", facts: "Creates bright red flames in fireworks." },
  { symbol: "Y", name: "Yttrium", atomicNumber: 39, atomicMass: "88.905", groupBlock: "Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d1", uses: "LEDs, superconductors", facts: "Used in color television tubes." },
  { symbol: "Zr", name: "Zirconium", atomicNumber: 40, atomicMass: "91.224", groupBlock: "Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d2", uses: "Nuclear reactors, jewelry", facts: "Highly corrosion-resistant." },
  { symbol: "Nb", name: "Niobium", atomicNumber: 41, atomicMass: "92.906", groupBlock: "Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d3", uses: "Steel alloys, superconducting magnets", facts: "Often used in jewelry for its bright appearance." },
  { symbol: "Mo", name: "Molybdenum", atomicNumber: 42, atomicMass: "95.95", groupBlock: "Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d5", uses: "Steel alloys, electrical contacts", facts: "Has the highest melting point of any pure metal." },
  { symbol: "Tc", name: "Technetium", atomicNumber: 43, atomicMass: "98", groupBlock: "Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d5", uses: "Medical imaging, radiotherapy", facts: "First element to be artificially produced." },
  { symbol: "Ru", name: "Ruthenium", atomicNumber: 44, atomicMass: "101.07", groupBlock: "Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d7", uses: "Electronics, solar cells", facts: "Part of the platinum group metals." },
  { symbol: "Rh", name: "Rhodium", atomicNumber: 45, atomicMass: "102.905", groupBlock: "Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d8", uses: "Catalysts, jewelry", facts: "Highly reflective and resistant to corrosion." },
  { symbol: "Pd", name: "Palladium", atomicNumber: 46, atomicMass: "106.42", groupBlock: "Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10", uses: "Catalysts, hydrogen storage", facts: "Absorbs large amounts of hydrogen." },
  { symbol: "Ag", name: "Silver", atomicNumber: 47, atomicMass: "107.868", groupBlock: "Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s1", uses: "Jewelry, coins, electronics", facts: "Best conductor of electricity and heat." },
  { symbol: "Cd", name: "Cadmium", atomicNumber: 48, atomicMass: "112.414", groupBlock: "Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10", uses: "Batteries, solar cells", facts: "Toxic if ingested or inhaled." },
  { symbol: "In", name: "Indium", atomicNumber: 49, atomicMass: "114.818", groupBlock: "Post-Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p1", uses: "Semiconductors, solar cells", facts: "Soft and easily fusible." },
  { symbol: "Sn", name: "Tin", atomicNumber: 50, atomicMass: "118.71", groupBlock: "Post-Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p2", uses: "Alloys, coatings", facts: "Used in solder and as a protective coating for steel." },
  { symbol: "Sb", name: "Antimony", atomicNumber: 51, atomicMass: "121.76", groupBlock: "Metalloid", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p3", uses: "Flame retardants, lead alloys", facts: "Used in ancient times for cosmetics." },
  { symbol: "Te", name: "Tellurium", atomicNumber: 52, atomicMass: "127.60", groupBlock: "Metalloid", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p4", uses: "Semiconductors, thermoelectric devices", facts: "Used in alloys to improve strength and machinability." },
  { symbol: "I", name: "Iodine", atomicNumber: 53, atomicMass: "126.904", groupBlock: "Halogen", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p5", uses: "Antiseptics, iodine tinctures", facts: "Essential for thyroid function." },
  { symbol: "Xe", name: "Xenon", atomicNumber: 54, atomicMass: "131.293", groupBlock: "Noble Gas", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6", uses: "Xenon lamps, anesthetics", facts: "One of the rarest elements in Earth's atmosphere." },
  { symbol: "Cs", name: "Caesium", atomicNumber: 55, atomicMass: "132.905", groupBlock: "Alkali Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 5p6 6s1", uses: "Atomic clocks, medical imaging", facts: "Has the lowest melting point of the alkali metals." },
  { symbol: "Ba", name: "Barium", atomicNumber: 56, atomicMass: "137.33", groupBlock: "Alkaline Earth Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 5p6 6s2", uses: "Medical imaging, fireworks", facts: "Used in barium meals for X-ray imaging." },
  { symbol: "La", name: "Lanthanum", atomicNumber: 57, atomicMass: "138.905", groupBlock: "Lanthanide", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 5p6 4f1 5d1 6s2", uses: "Camera lenses, catalysts", facts: "Named after the Greek word for 'hidden.'" },
  { symbol: "Ce", name: "Cerium", atomicNumber: 58, atomicMass: "140.116", groupBlock: "Lanthanide", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 5p6 4f2 5d1 6s2", uses: "Catalysts, glass polishing", facts: "Most abundant of the rare earth elements." },
  { symbol: "Pr", name: "Praseodymium", atomicNumber: 59, atomicMass: "140.907", groupBlock: "Lanthanide", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 5p6 4f3 6s2", uses: "Aircraft engines, magnets", facts: "Used in manufacturing high-strength magnets." },
  { symbol: "Nd", name: "Neodymium", atomicNumber: 60, atomicMass: "144.242", groupBlock: "Lanthanide", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 5p6 4f4 6s2", uses: "Neodymium magnets, laser technology", facts: "Known for its strong permanent magnets." },
  { symbol: "Pm", name: "Promethium", atomicNumber: 61, atomicMass: "145", groupBlock: "Lanthanide", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 5p6 4f5 6s2", uses: "Atomic batteries, research", facts: "Not found naturally on Earth; is radioactive." },
  { symbol: "Sm", name: "Samarium", atomicNumber: 62, atomicMass: "150.36", groupBlock: "Lanthanide", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 5p6 4f6 6s2", uses: "Magnets, cancer treatment", facts: "Used in the production of samarium-cobalt magnets." },
  { symbol: "Eu", name: "Europium", atomicNumber: 63, atomicMass: "151.98", groupBlock: "Lanthanide", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 5p6 4f7 6s2", uses: "Fluorescent lamps, lasers", facts: "One of the most reactive lanthanides." },
  { symbol: "Gd", name: "Gadolinium", atomicNumber: 64, atomicMass: "157.25", groupBlock: "Lanthanide", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 5p6 4f7 5d1 6s2", uses: "MRI contrast agents, neutron capture", facts: "Very effective in magnetic resonance imaging (MRI)." },
  { symbol: "Tb", name: "Terbium", atomicNumber: 65, atomicMass: "158.925", groupBlock: "Lanthanide", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 5p6 4f9 6s2", uses: "Phosphorescent materials, lasers", facts: "Used in the creation of green phosphors for color televisions." },
  { symbol: "Dy", name: "Dysprosium", atomicNumber: 66, atomicMass: "162.50", groupBlock: "Lanthanide", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 5p6 4f10 6s2", uses: "Magnetic materials, laser materials", facts: "Has a high magnetic susceptibility." },
  { symbol: "Ho", name: "Holmium", atomicNumber: 67, atomicMass: "164.930", groupBlock: "Lanthanide", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 5p6 4f11 6s2", uses: "Lasers, magnetic materials", facts: "Has the highest magnetic moment of any element." },
  { symbol: "Er", name: "Erbium", atomicNumber: 68, atomicMass: "167.259", groupBlock: "Lanthanide", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 5p6 4f12 6s2", uses: "Fiber-optic communications, lasers", facts: "Used in the manufacture of laser equipment." },
  { symbol: "Tm", name: "Thulium", atomicNumber: 69, atomicMass: "168.934", groupBlock: "Lanthanide", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 5p6 4f13 6s2", uses: "Lasers, medical imaging", facts: "Used in the manufacture of portable X-ray machines." },
  { symbol: "Yb", name: "Ytterbium", atomicNumber: 70, atomicMass: "173.04", groupBlock: "Lanthanide", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 5p6 4f14 6s2", uses: "Lasers, atomic clocks", facts: "Used in the manufacture of high-efficiency solar cells." },
  { symbol: "Lu", name: "Lutetium", atomicNumber: 71, atomicMass: "174.966", groupBlock: "Lanthanide", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 5p6 4f14 5d1 6s2", uses: "Medical imaging, catalysts", facts: "One of the heaviest lanthanides." },
  { symbol: "Hf", name: "Hafnium", atomicNumber: 72, atomicMass: "178.49", groupBlock: "Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d2", uses: "Nuclear reactors, electronics", facts: "Highly resistant to corrosion and used in nuclear applications." },
  { symbol: "Ta", name: "Tantalum", atomicNumber: 73, atomicMass: "180.947", groupBlock: "Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d3", uses: "Electronics, surgical instruments", facts: "Tantalum is highly corrosion-resistant, even to acids." },
  { symbol: "W", name: "Tungsten", atomicNumber: 74, atomicMass: "183.84", groupBlock: "Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d4", uses: "Light bulb filaments, cutting tools", facts: "Has the highest melting point of all metals." },
  { symbol: "Re", name: "Rhenium", atomicNumber: 75, atomicMass: "186.21", groupBlock: "Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d5", uses: "Jet engines, thermocouples", facts: "Rhenium is one of the rarest elements on Earth." },
  { symbol: "Os", name: "Osmium", atomicNumber: 76, atomicMass: "190.23", groupBlock: "Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d6", uses: "Electrical contacts, fountain pens", facts: "Osmium is the densest naturally occurring element." },
  { symbol: "Ir", name: "Iridium", atomicNumber: 77, atomicMass: "192.22", groupBlock: "Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d7", uses: "Spark plugs, jewelry", facts: "Iridium is one of the most corrosion-resistant metals." },
  { symbol: "Pt", name: "Platinum", atomicNumber: 78, atomicMass: "195.08", groupBlock: "Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d8", uses: "Catalysts, jewelry, cancer treatment", facts: "Platinum is highly resistant to corrosion and oxidation." },
  { symbol: "Au", name: "Gold", atomicNumber: 79, atomicMass: "196.97", groupBlock: "Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d9", uses: "Jewelry, electronics, dentistry", facts: "Gold is one of the most malleable and ductile metals." },
  { symbol: "Hg", name: "Mercury", atomicNumber: 80, atomicMass: "200.59", groupBlock: "Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Thermometers, barometers, electrical switches", facts: "Mercury is the only metal that is liquid at room temperature." },
  { symbol: "Tl", name: "Thallium", atomicNumber: 81, atomicMass: "204.38", groupBlock: "Post-Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Electronics, photoelectric cells", facts: "Thallium is toxic and has limited industrial use due to its toxicity." },
  { symbol: "Pb", name: "Lead", atomicNumber: 82, atomicMass: "207.2", groupBlock: "Post-Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Batteries, shielding from radiation", facts: "Lead is highly toxic and its use has been restricted in many applications." },
  { symbol: "Bi", name: "Bismuth", atomicNumber: 83, atomicMass: "208.98", groupBlock: "Post-Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Cosmetics, pharmaceuticals, alloys", facts: "Bismuth is the heaviest stable isotope known." },
  { symbol: "Po", name: "Polonium", atomicNumber: 84, atomicMass: "209", groupBlock: "Metalloid", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Radiation sources, nuclear research", facts: "Polonium is highly radioactive and was used in the assassination of Alexander Litvinenko." },
  { symbol: "At", name: "Astatine", atomicNumber: 85, atomicMass: "210", groupBlock: "Halogen", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Cancer treatment research", facts: "Astatine is the rarest naturally occurring halogen." },
  { symbol: "Rn", name: "Radon", atomicNumber: 86, atomicMass: "222", groupBlock: "Noble Gas", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Cancer treatment, radioactive tracing", facts: "Radon is a colorless, odorless, and tasteless gas that is radioactive." },
  { symbol: "Fr", name: "Francium", atomicNumber: 87, atomicMass: "223", groupBlock: "Alkali Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Research purposes", facts: "Francium is the least stable of the first 101 elements in the periodic table." },
  { symbol: "Ra", name: "Radium", atomicNumber: 88, atomicMass: "226", groupBlock: "Alkaline Earth Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Medical treatments, radiography", facts: "Radium is highly radioactive and was once used in luminous paint." },
  { symbol: "Ac", name: "Actinium", atomicNumber: 89, atomicMass: "227", groupBlock: "Actinide", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Radiation sources, research", facts: "Actinium is highly radioactive and was the first non-primordial radioactive element discovered." },
  { symbol: "Th", name: "Thorium", atomicNumber: 90, atomicMass: "232.04", groupBlock: "Actinide", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Nuclear reactors, aircraft engines", facts: "Thorium is considered a possible alternative to uranium in nuclear reactors." },
  { symbol: "Pa", name: "Protactinium", atomicNumber: 91, atomicMass: "231.04", groupBlock: "Actinide", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Research purposes", facts: "Protactinium is highly radioactive and was once used as a neutron source in early nuclear research." },
  { symbol: "U", name: "Uranium", atomicNumber: 92, atomicMass: "238.03", groupBlock: "Actinide", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Nuclear fuel, weapons", facts: "Uranium is a key element used in nuclear energy and has the highest atomic number of naturally occurring elements." },
  { symbol: "Np", name: "Neptunium", atomicNumber: 93, atomicMass: "237", groupBlock: "Actinide", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Nuclear research, fuel for nuclear reactors", facts: "Neptunium was the first transuranic element to be synthesized." },
  { symbol: "Pu", name: "Plutonium", atomicNumber: 94, atomicMass: "244", groupBlock: "Actinide", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Nuclear fuel, weapons", facts: "Plutonium is a radioactive metal and a key element in nuclear weapons and power generation." },
  { symbol: "Am", name: "Americium", atomicNumber: 95, atomicMass: "243", groupBlock: "Actinide", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Smoke detectors, nuclear batteries", facts: "Americium was used in the first commercial smoke detectors." },
  { symbol: "Cm", name: "Curium", atomicNumber: 96, atomicMass: "247", groupBlock: "Actinide", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Radiation sources, research", facts: "Curium is named after Marie and Pierre Curie, pioneers in the study of radioactivity." },
  { symbol: "Bk", name: "Berkelium", atomicNumber: 97, atomicMass: "247", groupBlock: "Actinide", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Research, nuclear fuel", facts: "Berkelium is a synthetic element and is named after Berkeley, California." },
  { symbol: "Cf", name: "Californium", atomicNumber: 98, atomicMass: "251", groupBlock: "Actinide", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Neutron sources, research", facts: "Californium is a radioactive element used in nuclear reactors and medical applications." },
  { symbol: "Es", name: "Einsteinium", atomicNumber: 99, atomicMass: "252", groupBlock: "Actinide", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Research, neutron sources", facts: "Einsteinium is named after Albert Einstein and is used in scientific research." },
  { symbol: "Fm", name: "Fermium", atomicNumber: 100, atomicMass: "257", groupBlock: "Actinide", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Research, neutron sources", facts: "Fermium is named after physicist Enrico Fermi and is used in nuclear science." },
  { symbol: "Md", name: "Mendelevium", atomicNumber: 101, atomicMass: "258", groupBlock: "Actinide", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Research, neutron sources", facts: "Mendelevium is named after Dmitri Mendeleev, the creator of the periodic table." },
  { symbol: "No", name: "Nobelium", atomicNumber: 102, atomicMass: "259", groupBlock: "Actinide", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Research", facts: "Nobelium is named after Alfred Nobel, the founder of the Nobel Prizes." },
  { symbol: "Lr", name: "Lawrencium", atomicNumber: 103, atomicMass: "262", groupBlock: "Actinide", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Research", facts: "Lawrencium is named after Ernest O. Lawrence, the inventor of the cyclotron." },
  { symbol: "Rf", name: "Rutherfordium", atomicNumber: 104, atomicMass: "267", groupBlock: "Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Research", facts: "Rutherfordium is named after physicist Ernest Rutherford, a pioneer of nuclear physics." },
  { symbol: "Db", name: "Dubnium", atomicNumber: 105, atomicMass: "270", groupBlock: "Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Research", facts: "Dubnium is named after Dubna, Russia, where it was first synthesized." },
  { symbol: "Sg", name: "Seaborgium", atomicNumber: 106, atomicMass: "271", groupBlock: "Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Research", facts: "Seaborgium is named after Glenn T. Seaborg, a chemist who contributed to the discovery of many elements." },
  { symbol: "Bh", name: "Bohrium", atomicNumber: 107, atomicMass: "270", groupBlock: "Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Research", facts: "Bohrium is named after Niels Bohr, a Danish physicist who made foundational contributions to understanding atomic structure." },
  { symbol: "Hs", name: "Hassium", atomicNumber: 108, atomicMass: "277", groupBlock: "Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Research", facts: "Hassium is named after the German state of Hesse, where it was first synthesized." },
  { symbol: "Mt", name: "Meitnerium", atomicNumber: 109, atomicMass: "278", groupBlock: "Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Research", facts: "Meitnerium is named after Lise Meitner, a physicist who worked on nuclear fission." },
  { symbol: "Ds", name: "Darmstadtium", atomicNumber: 110, atomicMass: "281", groupBlock: "Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Research", facts: "Darmstadtium is named after Darmstadt, Germany, where it was first synthesized." },
  { symbol: "Rg", name: "Roentgenium", atomicNumber: 111, atomicMass: "280", groupBlock: "Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Research", facts: "Roentgenium is named after Wilhelm Röntgen, the discoverer of X-rays." },
  { symbol: "Cn", name: "Copernicium", atomicNumber: 112, atomicMass: "285", groupBlock: "Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Research", facts: "Copernicium is named after Nicolaus Copernicus, the astronomer who formulated the heliocentric model of the universe." },
  { symbol: "Nh", name: "Nihonium", atomicNumber: 113, atomicMass: "284", groupBlock: "Post-Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Research", facts: "Nihonium is named after Japan (Nihon), the country where it was first synthesized." },
  { symbol: "Fl", name: "Flerovium", atomicNumber: 114, atomicMass: "289", groupBlock: "Post-Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Research", facts: "Flerovium is named after the Flerov Laboratory of Nuclear Reactions in Russia." },
  { symbol: "Mc", name: "Moscovium", atomicNumber: 115, atomicMass: "288", groupBlock: "Post-Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Research", facts: "Moscovium is named after Moscow, Russia, the location where it was first synthesized." },
  { symbol: "Lv", name: "Livermorium", atomicNumber: 116, atomicMass: "293", groupBlock: "Post-Transition Metal", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Research", facts: "Livermorium is named after the Lawrence Livermore National Laboratory in California, USA." },
  { symbol: "Ts", name: "Tennessine", atomicNumber: 117, atomicMass: "294", groupBlock: "Halogen", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Research", facts: "Tennessine is named after the state of Tennessee, USA, where much of its research was conducted." },
  { symbol: "Og", name: "Oganesson", atomicNumber: 118, atomicMass: "294", groupBlock: "Noble Gas", electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 4p6 5s2 4d10 5p6 6s2 4f14 5d10", uses: "Research", facts: "Oganesson is named after Yuri Oganessian, a Russian nuclear physicist who contributed to the discovery of superheavy elements." }
];

const table = document.getElementById("table");
const infoBox = document.getElementById("element-info");

elements.forEach(el => {
  const div = document.createElement("div");
  div.classList.add("element");
  div.innerHTML = `<strong>${el.symbol}</strong><span style="font-size:0.7em">${el.atomicNumber}</span>`;
  div.onclick = () => showInfo(el);
  table.appendChild(div);
});

function showInfo(el) {
  document.getElementById("element-name").textContent = el.name;
  document.getElementById("element-symbol").textContent = el.symbol;
  document.getElementById("element-number").textContent = el.atomicNumber;
  document.getElementById("element-mass").textContent = el.atomicMass;
  document.getElementById("element-group").textContent = el.groupBlock;
  document.getElementById("element-config").textContent = el.electronConfiguration;
  document.getElementById("element-uses").textContent = el.uses;
  document.getElementById("element-facts").textContent = el.facts;
  infoBox.classList.remove("hidden");
}

document.getElementById("close").onclick = () => infoBox.classList.add("hidden");
  